[package]
name = "free_bank"
version = "0.0.1"


[addresses]
StarcoinFramework = "0x1"
admin = "0x68d69DC32Ae00470C8c96793A5C9b560"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "cf1deda180af40a8b3e26c0c7b548c4c290cd7e7" }
